server:
  port: 8081

spring:
  kafka:
    consumer:
      group-id: "topic-article-readers"
      bootstrap-servers: localhost:9092
#
#    streams:
#      state-dir: /Users/a1/work/kafka-streams
#      application-id: my-kafka-streams-app
#    application:
#      name: my-spring-app

  data:
    mongodb:
      host: localhost
      port: 27017
      database: kafka-db

topic:
  name: docs.article
#  filtered-name: filtered.docs.article

